### ISSUE TITLE
Questions: Permission to use it to my own project. And a little bit about auth token

### ISSUE THREAD

**Issue by vader-pepe** [helmisatria/tweet-harvest#10]
Cool project you have there! 

I have a project that need this kind of function ([snorkel](https://github.com/chadwithz/snorkel)) and I wonder if I can use this (with some changes) in my project? 🙏

And one more thing. Since Im pretty new in crawling, I've seen you used only the auth_token from the logged in user and use that information to become a logged in user in the playwright. My project use a complete flow of logging in (inputting email and password) for simulating a real human. So I wonder if this technique is applicable to all platforms or just the X (formerly knows as Twitter)?

thanks

**Comment by chadwithz** [comment]
I learnt about cookies. It does work for all platforms
