### ISSUE TITLE
Crawling Tap Top Tweet or Latest Tweet

### ISSUE THREAD

**Issue by mbaht** [helmisatria/tweet-harvest#11]
Ijin tanya Bang.. Untuk yang sekarang alur crawlingnya melihat hasil dari Tab Latest terlebih dahulu jika tidak ada posting akan ganti ke Tab Top Tweet ya Bang?
Gmn caranya untuk bisa pilih buat crawling di Tab Top Tweet saja (seperti tutorial yang bulan Juni) bagaimana ya Bang?
Makasih sebelumnya

**Comment by helmisatria** [comment]
Fixed on this PR https://github.com/helmisatria/tweet-harvest/pull/16, now you can use `--search-tab` or `--tab` with the value of `TOP` or `LATEST`
