### ISSUE TITLE
SyntaxError: Unexpected token R in JSON at position 0

### ISSUE THREAD

**Issue by Ajmyquira** [helmisatria/tweet-harvest#12]
This is the screenshot generated:

![Error-05-09-2023_17-43-55](https://github.com/helmisatria/tweet-harvest/assets/46566715/86780444-e2ac-4a6b-9894-e56a37105810)

Systax error:

`SyntaxError: Unexpected token R in JSON at position 0
    at JSON.parse (<anonymous>)
    at Response.json (C:\Users\anton\AppData\Local\npm-cache\_npx\dfac722d76c7c5c9\node_modules\playwright-core\lib\client\network.js:401:17)`

What's the reason for this error? I'm using Tweet-harvest v 2.2.6.

Thanks.

**Comment by helmisatria** [comment]
Most likely, you have already exceeded the Twitter rate limit. I have created an MR for more declarative information if you have been rate-limited. You can find the MR at this link: [https://github.com/helmisatria/tweet-harvest/pull/13](https://github.com/helmisatria/tweet-harvest/pull/13)
