### ISSUE TITLE
latest version stops crawling after 200+ tweets

### ISSUE THREAD

**Issue by RandyTunru** [helmisatria/tweet-harvest#18]
I was trying out the new version since it seems that it is now possible to crawl from the "TOP" post tabs, but during crawling the tweet-harvest would stop around 200+ tweets unlike the previous version (2.2.8) despite having the same tweet prompt and even if im using the "LATEST" tab

**Comment by RandyTunru** [comment]
also if possible for the program to log which tab it is currently crawling from (e.g "Crawling from the 'TOP' tab" to be logged when the -tab is passed with "TOP"

**Comment by helmisatria** [comment]
Please create a new issue if you encounter the same problem. It should be resolved in the latest version.
