### ISSUE TITLE
Ada dokumentasi buat pakai alatnya ga bang? 

### ISSUE THREAD

**Issue by Kingki19** [helmisatria/tweet-harvest#21]
Misalnya parameter filter tanggal atau batasan usernya bang

**Comment by ghifarit53** [comment]
Bisa pakai command `tweet-harvest --help` bang, nanti muncul semua parameter yang bisa diganti. Buat filter tanggal bisa pake `--from` sama `--to`, kalau batas user maksudnya me-limit tweet hanya dari user tertentu ya, sepertinya nggak ada.

<img width="838" alt="Screenshot 2024-03-15 at 01 54 00" src="https://github.com/helmisatria/tweet-harvest/assets/59758342/c6561fbe-e944-4ffb-b88e-69a3dfe13a2a">
