### ISSUE TITLE
Version 2.2.8 has been removed from npx

### ISSUE THREAD

**Issue by manuelcastiblan** [helmisatria/tweet-harvest#23]
Version 2.2.8 has been removed from npx

![image](https://github.com/helmisatria/tweet-harvest/assets/28069241/42d5fd8e-ecaf-4af0-a66a-d6dadb531492)
![image](https://github.com/helmisatria/tweet-harvest/assets/28069241/7f52019d-d03b-4de9-9bec-e90f6ee60bc4)

**Comment by achmadrizkin** [comment]
yeah i get that issue too

**Comment by Kingki19** [comment]
I think it changes from `2.2.8` to version `2.6.0`, i got this error to when helping my lecturers

**Comment by helmisatria** [comment]
Use the latest version
