### ISSUE TITLE
invalid auth token

### ISSUE THREAD

**Issue by Mustachy** [helmisatria/tweet-harvest#25]
Hi mas Helmi, sebelumnya thanks untuk tweet-harvest-nya karena kepake banget buat skripsi saya.

Cuma mau raise issue nih mas, sepertinya codingan nya harus diupdate karena saya (dan dari beberapa orang yang pakai saya lihat di komen youtube) dapat error invalid auth token meskipun sudah benar, diganti pakai auth token dari akun lain sudah ngga invalid auth token lagi, tapi ngga dapat apa-apa dari scrolling/scrapping nya, mungkin bisa dibantu di fix mas Helmi.

Thanks mas!

**Comment by thisisbintang** [comment]
#26

**Comment by helmisatria** [comment]
should be fixed in the latest version
