### ISSUE TITLE
How to scrape the tweets on spesific date

### ISSUE THREAD

**Issue by kokohandoko00** [helmisatria/tweet-harvest#4]
Hello Mas Helmi, thanks for your work. This tools helps me to scrape tweets for my thesis. You are like life-saviour because a few days ago snscrape didn't work anymore. So this tools helps me so much. 

But I am wondering, can I get a tweets on spesific date? 

Maybe that's all from me, thanks.

**Comment by helmisatria** [comment]
Hi there! I’m glad to hear that the tool has been helpful to you. To filter tweets on a specific date, you can use the “–from” and “–to” options in the command. For example, you can run the following command to get tweets about “Lampung” that were tweeted between January 1st, 2023, and February 1st, 2023:

```
npx tweet-harvest@0.0.35 --from 01-01-2023 --to 01-02-2023 -s "Lampung"
```

I hope that helps answer your question. Feel free to let me know if you have any more questions.
